# Generated by Django 5.2.5 on 2025-08-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(max_length=2048)),
                ('code', models.SlugField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='shorty_link_code_f49661_idx'), models.Index(fields=['long_url'], name='shorty_link_long_ur_655785_idx')],
            },
        ),
    ]
