# Generated by Django 5.2.5 on 2025-08-14 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='link',
            name='shorty_link_code_f49661_idx',
        ),
        migrations.RemoveIndex(
            model_name='link',
            name='shorty_link_long_ur_655785_idx',
        ),
        migrations.AlterField(
            model_name='link',
            name='code',
            field=models.SlugField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='long_url',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
    ]
